# Generated by Django 5.0.1 on 2024-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=300)),
            ],
        ),
    ]
